"""initial schema

Revision ID: 001_initial_schema
Revises:
Create Date: 2025-10-24 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ticker table
    op.create_table(
        "ticker",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("market_cap", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol"),
    )

    # Create run table
    op.create_table(
        "run",
        sa.Column("run_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("strategy", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("tickers_processed", sa.Integer(), nullable=True),
        sa.Column("candidates_found", sa.Integer(), nullable=True),
        sa.Column("errors_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index("idx_run_date_strategy", "run", ["run_date", "strategy"], unique=False)
    op.create_index("idx_run_status", "run", ["status"], unique=False)
    op.create_unique_constraint("uq_run_date_strategy", "run", ["run_date", "strategy"])

    # Create feature table
    op.create_table(
        "feature",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("ticker_symbol", sa.String(length=10), nullable=False),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("asof", sa.Date(), nullable=False),
        sa.Column("strategy", sa.String(length=50), nullable=False),
        sa.Column("feature_version", sa.String(length=20), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ticker_symbol"], ["ticker.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_feature_ticker_asof_strategy",
        "feature",
        ["ticker_symbol", "asof", "strategy"],
        unique=False,
    )
    op.create_index("idx_feature_strategy_asof", "feature", ["strategy", "asof"], unique=False)
    op.create_unique_constraint(
        "uq_feature_ticker_run_strategy", "feature", ["ticker_symbol", "run_id", "strategy"]
    )

    # Create candidate table
    op.create_table(
        "candidate",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("ticker_symbol", sa.String(length=10), nullable=False),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("asof", sa.Date(), nullable=False),
        sa.Column("strategy", sa.String(length=50), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("drop_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("volume_rvol", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("rationale", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ticker_symbol"], ["ticker.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_candidate_asof_strategy", "candidate", ["asof", "strategy"], unique=False)
    op.create_index(
        "idx_candidate_ticker_asof", "candidate", ["ticker_symbol", "asof"], unique=False
    )
    op.create_index("idx_candidate_score", "candidate", ["score"], unique=False)
    op.create_unique_constraint(
        "uq_candidate_ticker_asof_strategy", "candidate", ["ticker_symbol", "asof", "strategy"]
    )

    # Create eval_outcome table
    op.create_table(
        "eval_outcome",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("candidate_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("recovery_detected", sa.Boolean(), nullable=False),
        sa.Column("recovery_days", sa.Integer(), nullable=True),
        sa.Column("max_recovery_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("return_t1", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("return_t3", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("return_t5", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("return_proxy", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column(
            "labeled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("labeling_version", sa.String(length=20), nullable=False),
        sa.Column("outcome_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id"),
    )
    op.create_index("idx_outcome_recovery", "eval_outcome", ["recovery_detected"], unique=False)
    op.create_index("idx_outcome_labeled_at", "eval_outcome", ["labeled_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_outcome_labeled_at", table_name="eval_outcome")
    op.drop_index("idx_outcome_recovery", table_name="eval_outcome")
    op.drop_table("eval_outcome")
    op.drop_index("idx_candidate_score", table_name="candidate")
    op.drop_index("idx_candidate_ticker_asof", table_name="candidate")
    op.drop_index("idx_candidate_asof_strategy", table_name="candidate")
    op.drop_table("candidate")
    op.drop_index("idx_feature_strategy_asof", table_name="feature")
    op.drop_index("idx_feature_ticker_asof_strategy", table_name="feature")
    op.drop_table("feature")
    op.drop_index("idx_run_status", table_name="run")
    op.drop_index("idx_run_date_strategy", table_name="run")
    op.drop_table("run")
    op.drop_table("ticker")
    # ### end Alembic commands ###
