/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Basic health check
         * @description Returns basic service health status
         */
        get: operations["health_check_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detailed health check
         * @description Returns detailed service health with database and system information
         */
        get: operations["detailed_health_check_v1_health_detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Kubernetes-style readiness probe - returns 200 if ready to serve traffic
         */
        get: operations["readiness_check_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Kubernetes-style liveness probe - returns 200 if service is alive
         */
        get: operations["liveness_check_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Scan
         * @description Trigger a new market scan.
         *
         *     This endpoint initiates a scan asynchronously and returns immediately
         *     with run IDs. The actual scan executes in the background.
         *
         *     **Process**:
         *     1. Validate request parameters
         *     2. Check for existing runs (unless force=true)
         *     3. Create Run records in database with status=pending
         *     4. Queue background task
         *     5. Return run IDs immediately
         *
         *     **Status Codes**:
         *     - 202: Scan queued successfully
         *     - 400: Invalid request (empty strategies, etc.)
         *     - 409: Scan already exists for date/strategy (unless force=true)
         *     - 500: Server error
         *
         *     Args:
         *         request: Scan request parameters
         *         background_tasks: FastAPI background tasks
         *         db: Database session
         *
         *     Returns:
         *         ScanResponse with run IDs and status
         */
        post: operations["trigger_scan_v1_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scan/{run_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Status
         * @description Get status of a specific scan run.
         *
         *     **Status Values**:
         *     - `pending`: Scan created but not started
         *     - `running`: Scan currently executing
         *     - `completed`: Scan finished successfully
         *     - `failed`: Scan encountered errors
         *
         *     **Status Codes**:
         *     - 200: Status retrieved successfully
         *     - 404: Run ID not found
         *
         *     Args:
         *         run_id: Unique run identifier
         *         db: Database session
         *
         *     Returns:
         *         ScanStatusResponse with current status
         */
        get: operations["get_scan_status_v1_scan__run_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scan/logs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream scan logs in real-time
         * @description Stream log events for a specific scan run using Server-Sent Events (SSE).
         *
         *         The client should connect with EventSource or similar SSE client:
         *         ```javascript
         *         const eventSource = new EventSource('/v1/scan/logs/{run_id}');
         *         eventSource.onmessage = (event) => {
         *             const log = JSON.parse(event.data);
         *             console.log(log.message);
         *         };
         *         ```
         *
         *         Each event contains:
         *         - `timestamp`: ISO 8601 timestamp
         *         - `level`: Log level (info, warning, error)
         *         - `message`: Log message
         *         - `ticker`: Ticker symbol (if applicable)
         *         - `strategy`: Strategy name (if applicable)
         *         - `score`: Candidate score (if applicable)
         *
         *         The stream automatically closes when the scan completes or the client disconnects.
         */
        get: operations["stream_scan_logs_v1_scan_logs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat with AI assistant
         * @description Send a message to the AI assistant for conversational interaction.
         *
         *         The assistant can:
         *         - Trigger market scans
         *         - Explain strategies
         *         - Answer questions about the system
         *
         *         Requires OPENAI_API_KEY environment variable to be set.
         */
        post: operations["chat_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Candidates
         * @description List recovery candidates with filtering, pagination, and sorting.
         *
         *     Returns a paginated list of candidates identified by scan runs. Results can be
         *     filtered by date, strategy, and minimum score. Supports sorting by multiple fields.
         *
         *     **Default behavior** (no filters):
         *     - Returns candidates from the most recent scan date
         *     - All strategies included
         *     - All scores included
         *     - Sorted by score (highest first)
         *
         *     **Pagination**:
         *     - Use `limit` and `offset` for pagination
         *     - Default: 50 items per page
         *     - Maximum: 500 items per page
         *
         *     **Sorting**:
         *     - `score`: Recovery probability (default: descending)
         *     - `drop_pct`: Drop percentage (default: descending for largest drops)
         *     - `ticker`: Alphabetical by ticker symbol
         *     - `volume_rvol`: Relative volume
         */
        get: operations["list_candidates_v1_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/candidate/{ticker}/{asof}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Candidate Detail
         * @description Get detailed information for a specific candidate.
         *
         *     Returns comprehensive details including:
         *     - Full scoring rationale and confidence factors
         *     - Data source attribution for transparency
         *     - Company information (name, sector)
         *     - Associated scan run metadata
         *
         *     If multiple strategies identified the same ticker on the same date,
         *     use the `strategy` query parameter to specify which one. If not provided,
         *     returns the candidate with the highest score.
         */
        get: operations["get_candidate_detail_v1_candidate__ticker___asof__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/by-date/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs By Date
         * @description List all scan runs for a specific date.
         *
         *     Returns all runs (across all strategies) that were executed for the given market date.
         *     This includes runs in any status: pending, running, completed, or failed.
         *
         *     **Use cases**:
         *     - Check which strategies ran on a specific date
         *     - Monitor scan execution status
         *     - Troubleshoot failed scans
         *     - Track scan performance over time
         *
         *     **Response**:
         *     - Returns runs sorted by start time (most recent first)
         *     - Includes timing and performance metrics when available
         *     - Shows error details for failed runs
         */
        get: operations["list_runs_by_date_v1_runs_by_date__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Detail
         * @description Get detailed information about a specific run.
         *
         *     Returns comprehensive details about a scan run including:
         *     - Timing information (start, completion, duration)
         *     - Performance metrics (tickers processed, candidates found)
         *     - Status and error information
         *     - Strategy configuration
         *
         *     **Use cases**:
         *     - Monitor scan progress (for running scans)
         *     - Analyze scan performance
         *     - Debug failed scans
         *     - Audit scan execution
         */
        get: operations["get_run_detail_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metrics
         * @description Get aggregate performance metrics across runs and candidates.
         *
         *     Returns comprehensive metrics to evaluate strategy performance:
         *     - **Run metrics**: Total runs, success rate, failure rate
         *     - **Candidate metrics**: Total identified, average per run, average score
         *     - **Evaluation metrics**: Hit rate, average returns, recovery time
         *
         *     **Time filtering**:
         *     - If no dates provided: Returns all-time metrics
         *     - If only start_date: Returns metrics from start_date onwards
         *     - If only end_date: Returns metrics up to end_date
         *     - If both: Returns metrics for the date range (inclusive)
         *
         *     **Strategy filtering**:
         *     - If strategy provided: Returns metrics for that strategy only
         *     - If not provided: Returns aggregate metrics across all strategies
         *
         *     **Use cases**:
         *     - Monitor overall system performance
         *     - Compare strategies over time
         *     - Track improvement in hit rates
         *     - Analyze return distributions
         *     - Identify best-performing periods
         */
        get: operations["get_metrics_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CandidateDetailResponse
         * @description Response model for detailed candidate view.
         */
        CandidateDetailResponse: {
            /**
             * Ticker
             * @description Stock ticker symbol
             */
            ticker: string;
            /**
             * Name
             * @description Company name
             */
            name?: string | null;
            /**
             * Sector
             * @description Industry sector
             */
            sector?: string | null;
            /**
             * Asof
             * Format: date
             * @description Market date of identification
             */
            asof: string;
            /**
             * Strategy
             * @description Strategy that identified this candidate
             */
            strategy: string;
            /**
             * Score
             * @description Recovery probability score (0-1)
             */
            score: number;
            /**
             * Price
             * @description Price at identification
             */
            price?: number | null;
            /**
             * Drop Pct
             * @description Drop percentage that triggered alert
             */
            drop_pct?: number | null;
            /**
             * Volume Rvol
             * @description Relative volume vs average
             */
            volume_rvol?: number | null;
            /**
             * Rationale
             * @description Score rationale and confidence factors
             */
            rationale: {
                [key: string]: unknown;
            };
            /**
             * Attribution
             * @description Data source attribution for transparency
             */
            attribution: {
                [key: string]: unknown;
            };
            /**
             * Run Id
             * @description UUID of the scan run
             */
            run_id: string;
            /**
             * Run Status
             * @description Status of the scan run
             */
            run_status: string;
        };
        /**
         * CandidateItem
         * @description Individual candidate item in list response.
         */
        CandidateItem: {
            /**
             * Ticker
             * @description Stock ticker symbol
             */
            ticker: string;
            /**
             * Asof
             * Format: date
             * @description Market date of identification
             */
            asof: string;
            /**
             * Strategy
             * @description Strategy that identified this candidate
             */
            strategy: string;
            /**
             * Score
             * @description Recovery probability score (0-1)
             */
            score: number;
            /**
             * Price
             * @description Price at identification
             */
            price?: number | null;
            /**
             * Drop Pct
             * @description Drop percentage that triggered alert
             */
            drop_pct?: number | null;
            /**
             * Volume Rvol
             * @description Relative volume vs average
             */
            volume_rvol?: number | null;
            /**
             * Run Id
             * @description UUID of the scan run
             */
            run_id: string;
        };
        /**
         * CandidateListResponse
         * @description Response model for candidate listing.
         */
        CandidateListResponse: {
            /**
             * Candidates
             * @description List of candidates
             */
            candidates: components["schemas"]["CandidateItem"][];
            /**
             * Total
             * @description Total number of candidates matching filters
             */
            total: number;
            /**
             * Page
             * @description Current page number (1-indexed)
             */
            page: number;
            /**
             * Page Size
             * @description Number of items per page
             */
            page_size: number;
            /**
             * Filters
             * @description Applied filters for reference
             */
            filters: {
                [key: string]: unknown;
            };
        };
        /**
         * ChatRequest
         * @description Request model for chat endpoint.
         */
        ChatRequest: {
            /**
             * Message
             * @description User message to the AI assistant
             */
            message: string;
            /**
             * Conversation Id
             * @description Optional conversation ID for context
             */
            conversation_id?: string | null;
        };
        /**
         * ChatResponse
         * @description Response model for chat endpoint.
         */
        ChatResponse: {
            /**
             * Message
             * @description Assistant's response message
             */
            message: string;
            /**
             * Tool Calls
             * @description Tools executed
             */
            tool_calls?: components["schemas"]["ToolCall"][];
            /**
             * Conversation Id
             * @description Conversation ID
             */
            conversation_id?: string | null;
        };
        /**
         * DetailedHealthResponse
         * @description Detailed health check response with system info.
         */
        DetailedHealthResponse: {
            /** Status */
            status: string;
            /** Timestamp */
            timestamp: string;
            /** Version */
            version: string;
            /** Database */
            database: {
                [key: string]: unknown;
            };
            /** System */
            system: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response model.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Timestamp */
            timestamp: string;
            /** Version */
            version: string;
            /** Database */
            database: string;
            /** Checks */
            checks?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * MetricsResponse
         * @description Response model for aggregate metrics.
         */
        MetricsResponse: {
            /**
             * Start Date
             * @description Start date of metrics period
             */
            start_date?: string | null;
            /**
             * End Date
             * @description End date of metrics period
             */
            end_date?: string | null;
            /**
             * Strategy
             * @description Strategy filter applied
             */
            strategy?: string | null;
            /**
             * Total Runs
             * @description Total number of scan runs
             */
            total_runs: number;
            /**
             * Successful Runs
             * @description Number of successful runs
             */
            successful_runs: number;
            /**
             * Failed Runs
             * @description Number of failed runs
             */
            failed_runs: number;
            /**
             * Total Candidates
             * @description Total candidates identified
             */
            total_candidates: number;
            /**
             * Avg Candidates Per Run
             * @description Average candidates per successful run
             */
            avg_candidates_per_run?: number | null;
            /**
             * Avg Score
             * @description Average recovery probability score
             */
            avg_score?: number | null;
            /**
             * Evaluated Candidates
             * @description Number of candidates with labeled outcomes
             */
            evaluated_candidates: number;
            /**
             * Recoveries
             * @description Number of successful recoveries
             */
            recoveries?: number | null;
            /**
             * Hit Rate
             * @description Recovery hit rate (recoveries / evaluated)
             */
            hit_rate?: number | null;
            /**
             * Avg Return Proxy
             * @description Average return proxy for recoveries
             */
            avg_return_proxy?: number | null;
            /**
             * Avg Recovery Days
             * @description Average days to recovery
             */
            avg_recovery_days?: number | null;
        };
        /**
         * RunDetailResponse
         * @description Response model for detailed run view.
         */
        RunDetailResponse: {
            /**
             * Run Id
             * @description UUID of the scan run
             */
            run_id: string;
            /**
             * Run Date
             * Format: date
             * @description Market date of the scan
             */
            run_date: string;
            /**
             * Strategy
             * @description Strategy name
             */
            strategy: string;
            /**
             * Status
             * @description Run status: pending, running, completed, failed
             */
            status: string;
            /**
             * Started At
             * @description Scan start time (ISO 8601)
             */
            started_at?: string | null;
            /**
             * Completed At
             * @description Scan completion time (ISO 8601)
             */
            completed_at?: string | null;
            /**
             * Duration Seconds
             * @description Scan duration in seconds
             */
            duration_seconds?: number | null;
            /**
             * Tickers Processed
             * @description Number of tickers processed
             */
            tickers_processed?: number | null;
            /**
             * Candidates Found
             * @description Number of candidates found
             */
            candidates_found?: number | null;
            /**
             * Errors Count
             * @description Number of errors encountered
             * @default 0
             */
            errors_count: number;
            /**
             * Error Details
             * @description Detailed error information
             */
            error_details?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RunItem
         * @description Individual run item in list response.
         */
        RunItem: {
            /**
             * Run Id
             * @description UUID of the scan run
             */
            run_id: string;
            /**
             * Run Date
             * Format: date
             * @description Market date of the scan
             */
            run_date: string;
            /**
             * Strategy
             * @description Strategy name
             */
            strategy: string;
            /**
             * Status
             * @description Run status: pending, running, completed, failed
             */
            status: string;
            /**
             * Duration Seconds
             * @description Scan duration in seconds
             */
            duration_seconds?: number | null;
            /**
             * Tickers Processed
             * @description Number of tickers processed
             */
            tickers_processed?: number | null;
            /**
             * Candidates Found
             * @description Number of candidates found
             */
            candidates_found?: number | null;
            /**
             * Errors Count
             * @description Number of errors encountered
             * @default 0
             */
            errors_count: number;
        };
        /**
         * RunListResponse
         * @description Response model for run listing.
         */
        RunListResponse: {
            /**
             * Runs
             * @description List of runs
             */
            runs: components["schemas"]["RunItem"][];
            /**
             * Total
             * @description Total number of runs
             */
            total: number;
            /**
             * Date
             * Format: date
             * @description Queried date
             */
            date: string;
        };
        /**
         * ScanRequest
         * @description Request to trigger a new scan.
         */
        ScanRequest: {
            /**
             * Strategies
             * @description List of strategy names to execute (null = all enabled strategies)
             * @example [
             *       "drop5"
             *     ]
             * @example [
             *       "drop5",
             *       "breakout"
             *     ]
             */
            strategies?: string[] | null;
            /**
             * Date
             * @description Market date to scan (null = today)
             * @example 2025-10-24
             */
            date?: string | null;
            /**
             * Force
             * @description Force re-run even if scan already exists for date/strategy
             * @default false
             */
            force: boolean;
        };
        /**
         * ScanResponse
         * @description Response from triggering a scan.
         * @example {
         *       "date": "2025-10-24",
         *       "message": "Scan queued for execution",
         *       "run_ids": [
         *         "550e8400-e29b-41d4-a716-446655440000"
         *       ],
         *       "status": "queued",
         *       "strategies": [
         *         "drop5"
         *       ]
         *     }
         */
        ScanResponse: {
            /**
             * Run Ids
             * @description List of run IDs for triggered scans (one per strategy)
             */
            run_ids: string[];
            /**
             * Status
             * @description Initial status of the scan
             * @example queued
             * @example running
             */
            status: string;
            /**
             * Strategies
             * @description List of strategies being executed
             */
            strategies: string[];
            /**
             * Date
             * Format: date
             * @description Market date being scanned
             */
            date: string;
            /**
             * Message
             * @description Human-readable status message
             */
            message: string;
        };
        /**
         * ScanStatusResponse
         * @description Status of a specific scan run.
         * @example {
         *       "candidates_found": 23,
         *       "completed_at": "2025-10-24T16:38:45Z",
         *       "duration_seconds": 525,
         *       "errors_count": 0,
         *       "run_date": "2025-10-24",
         *       "run_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "started_at": "2025-10-24T16:30:00Z",
         *       "status": "completed",
         *       "strategy": "drop5",
         *       "tickers_processed": 1500
         *     }
         */
        ScanStatusResponse: {
            /**
             * Run Id
             * @description Unique run identifier
             */
            run_id: string;
            /**
             * Run Date
             * Format: date
             * @description Market date of the scan
             */
            run_date: string;
            /**
             * Strategy
             * @description Strategy name
             */
            strategy: string;
            /**
             * Status
             * @description Current status: pending, running, completed, failed
             * @example pending
             * @example running
             * @example completed
             * @example failed
             */
            status: string;
            /**
             * Started At
             * @description When the scan started (null if not started)
             */
            started_at?: string | null;
            /**
             * Completed At
             * @description When the scan completed (null if not complete)
             */
            completed_at?: string | null;
            /**
             * Duration Seconds
             * @description Total duration in seconds (null if not complete)
             */
            duration_seconds?: number | null;
            /**
             * Tickers Processed
             * @description Number of tickers scanned (null if not complete)
             */
            tickers_processed?: number | null;
            /**
             * Candidates Found
             * @description Number of candidates identified (null if not complete)
             */
            candidates_found?: number | null;
            /**
             * Errors Count
             * @description Number of errors encountered
             * @default 0
             */
            errors_count: number;
            /**
             * Error Details
             * @description Error information if status=failed
             */
            error_details?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ToolCall
         * @description Information about a tool that was called.
         */
        ToolCall: {
            /**
             * Tool
             * @description Tool name
             */
            tool: string;
            /**
             * Status
             * @description Tool execution status
             */
            status: string;
            /**
             * Result
             * @description Tool execution result
             */
            result?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    detailed_health_check_v1_health_detailed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedHealthResponse"];
                };
            };
        };
    };
    readiness_check_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    liveness_check_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    trigger_scan_v1_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_status_v1_scan__run_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_scan_logs_v1_scan_logs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the scan run */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_v1_candidates_get: {
        parameters: {
            query?: {
                /** @description Filter by market date (YYYY-MM-DD). Defaults to most recent. */
                date?: string | null;
                /** @description Filter by strategy name */
                strategy?: string | null;
                /** @description Minimum recovery probability score */
                min_score?: number | null;
                /** @description Number of results per page */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
                /** @description Sort field: score, drop_pct, ticker, or volume_rvol */
                sort_by?: string;
                /** @description Sort order: asc or desc */
                sort_order?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidate_detail_v1_candidate__ticker___asof__get: {
        parameters: {
            query?: {
                /** @description Filter by strategy name */
                strategy?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
                asof: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_by_date_v1_runs_by_date__date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_v1_metrics_get: {
        parameters: {
            query?: {
                /** @description Start date for metrics (inclusive) */
                start_date?: string | null;
                /** @description End date for metrics (inclusive) */
                end_date?: string | null;
                /** @description Filter by strategy name */
                strategy?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
